
INSERT INTO disciplina (codigo, nome, descricao, semestre) VALUES
    ('CB0534', 'CÁLCULO DIFERENCIAL E INTEGRAL I', 'Introdução ao cálculo, incluindo limites, derivadas e integrais de funções de uma variável real. Fundamentos essenciais para a compreensão matemática em computação.', 1),
    ('CB0661', 'MATEMÁTICA DISCRETA', 'Estudo de estruturas matemáticas discretas, lógica, teoria dos conjuntos, relações, funções, indução matemática e teoria dos números. Base fundamental para ciência da computação.', 1),
    ('CK0169', 'CIRCUITOS DIGITAIS', 'Fundamentos de sistemas digitais, álgebra booleana, portas lógicas, circuitos combinacionais e sequenciais. Introdução à arquitetura básica de computadores.', 1),
    ('CK0211', 'FUNDAMENTOS DE PROGRAMAÇÃO', 'Introdução aos conceitos básicos de programação, algoritmos, tipos de dados, estruturas de controle e funções. Primeira experiência com desenvolvimento de software.', 1),
    ('CK0253', 'SEMINÁRIOS EM COMPUTAÇÃO', 'Apresentação e discussão de temas atuais em computação, preparando os alunos para a realidade profissional e acadêmica da área.', 1),
    ('CB0535', 'CÁLCULO DIFERENCIAL E INTEGRAL II', 'Continuação do Cálculo I, abordando integrais múltiplas, séries, sequências e cálculo vetorial. Aplicações em problemas computacionais.', 2),
    ('CB0589', 'ÁLGEBRA LINEAR', 'Estudo de matrizes, sistemas lineares, espaços vetoriais e transformações lineares. Fundamental para computação gráfica e machine learning.', 2),
    ('CK0170', 'TRANSMISSAO DE DADOS', 'Princípios de comunicação de dados, protocolos, modulação e técnicas de transmissão. Base para entendimento de redes de computadores.', 2),
    ('CK0209', 'ESTRUTURAS DE DADOS', 'Estudo de estruturas de dados fundamentais como listas, pilhas, filas, árvores e grafos. Análise de algoritmos e complexidade computacional.', 2),
    ('CK0226', 'PROGRAMAÇÃO', 'Aprofundamento em técnicas de programação, incluindo orientação a objetos, tratamento de exceções e interfaces gráficas.', 2),
    ('CC0261', 'INTRODUÇÃO A PROBABILIDADE E A ESTATÍSTICA', 'Conceitos fundamentais de probabilidade e estatística, incluindo distribuições, estimação e testes de hipóteses. Aplicações em análise de dados.', 3),
    ('CK0111', 'ALGORITMOS EM GRAFOS', 'Teoria dos grafos e seus algoritmos, incluindo busca, caminhos mínimos, árvores geradoras e fluxos em redes.', 3),
    ('CK0195', 'ARQUITETURA DE COMPUTADORES', 'Organização e arquitetura de computadores, conjunto de instruções, pipeline, hierarquia de memória e entrada/saída.', 3),
    ('CK0220', 'LÓGICA PARA CIÊNCIA DA COMPUTAÇÃO', 'Lógica proposicional e de predicados, métodos de prova e sua aplicação na verificação de programas.', 3),
    ('CK0235', 'TÉCNICAS DE PROGRAMAÇÃO I', 'Técnicas avançadas de programação, padrões de projeto, desenvolvimento de software em camadas e boas práticas.', 3),
    ('CK0047', 'MÉTODOS NUMÉRICOS I', 'Métodos computacionais para resolução de problemas matemáticos, incluindo equações não-lineares e sistemas lineares.', 4),
    ('CK0114', 'FUNDAMENTOS DE BANCOS DE DADOS', 'Conceitos fundamentais de banco de dados, modelo relacional, normalização e linguagem SQL.', 4),
    ('CK0115', 'LINGUAGENS DE PROGRAMAÇÃO I', 'Estudo comparativo de diferentes paradigmas de programação e suas características principais.', 4),
    ('CK0203', 'CONSTRUÇÃO E ANÁLISE DE ALGORITMOS', 'Técnicas de projeto e análise de algoritmos, complexidade computacional e otimização.', 4),
    ('CK0245', 'COMPUTAÇÃO GRÁFICA I', 'Fundamentos de computação gráfica, transformações geométricas, renderização e processamento de imagens.', 4),
    ('CK0048', 'MÉTODOS NUMÉRICOS II', 'Continuação de Métodos Numéricos I, abordando interpolação, integração numérica e equações diferenciais.', 5),
    ('CK0117', 'SISTEMAS DE GERENCIAMENTO DE BANCOS DE DADOS', 'Arquitetura de SGBDs, processamento de consultas, controle de concorrência e recuperação de falhas.', 5),
    ('CK0247', 'ENGENHARIA DE SOFTWARE I', 'Processo de desenvolvimento de software, requisitos, projeto, implementação, testes e manutenção.', 5),
    ('CK0249', 'REDES DE COMPUTADORES I', 'Arquitetura de redes, protocolos de comunicação, modelo OSI e TCP/IP, roteamento e segurança.', 5),
    ('CK0118', 'AUTOMATOS E LINGUAGENS FORMAIS', 'Teoria de autômatos, linguagens regulares e livres de contexto, máquinas de Turing e computabilidade.', 6),
    ('CK0192', 'ANÁLISE E PROJETO DE SISTEMAS I', 'Metodologias e ferramentas para análise e projeto de sistemas de software, incluindo UML e padrões de projeto.', 6),
    ('CK0234', 'SISTEMAS OPERACIONAIS', 'Conceitos e implementação de sistemas operacionais, processos, threads, gerenciamento de memória e sistemas de arquivos.', 6),
    ('CK0248', 'INTELIGÊNCIA ARTIFICIAL', 'Fundamentos de IA, busca, representação do conhecimento, aprendizado de máquina e processamento de linguagem natural.', 6),
    ('CK0101', 'TEORIA DA COMPUTAÇÃO', 'Estudo da computabilidade, decidibilidade, complexidade computacional e limites da computação.', 7),
    ('CK0202', 'CONSTRUÇÃO DE COMPILADORES', 'Teoria e implementação de compiladores, análise léxica, sintática e semântica, geração de código.', 7),
    ('CK0212', 'INFORMÁTICA E SOCIEDADE', 'Impactos sociais, éticos e profissionais da computação na sociedade contemporânea.', 7); 